name: alphatrade_app
description: A simple Flutter app for AlphaTrade AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.9.0
  http: ^0.13.4

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite